version: "3"
services:
  php-apache:
    hostname: task3
    container_name: apache-php
    build: apache-php
    restart: always
    volumes:
      - ./apache-php/src:/var/www/html-dynamic/dynamic
      - ./apache-php/ports.conf:/etc/apache2/ports.conf
      - ./apache-php/000-default.conf:/etc/apache2/sites-available/000-default.conf
  ngnix:
    container_name: nginx
    build: nginx
    restart: always
    volumes:
      - ./css:/usr/share/nginx/html-static/css
      - ./nginx/src:/usr/share/nginx/html-static/static
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8082:8082"
  db:
    container_name: mysql
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: appDB
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - './db:/docker-entrypoint-initdb.d'
      # - datadir:/var/lib/mysql
    ports:
      - "3306:3306"
    command: --character-set-server=utf8mb4
# volumes:
#   datadir:


    # db:
  #   container_name: task3_db
  #   image: mariadb
  #   restart: always
  #   ports:
  #     - "3306:3306"
  #   command: --character-set-server=utf8mb4
  #   volumes:
  #     - ./server:/docker-entrypoint-initdb.d
  #     - datadir:/var/lib/mysql
  #   environment:
  #     - MARIADB_ALLOW_EMPTY_ROOT_PASSWORD=1