version: "3"
services:
  db:
    container_name: task2_db
    image: mariadb
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - ./server:/docker-entrypoint-initdb.d
       - datadir:/var/lib/mysql

    environment:
      - MARIADB_ALLOW_EMPTY_ROOT_PASSWORD=1
  server:
    container_name: task2_server
    build: ./server
    restart: always
    volumes:
      - ./server:/var/www/html
    ports:
      - "8080:80"
volumes:
  datadir: